### ISSUE TITLE
doesn't go on termux

### ISSUE THREAD

**Issue by xAvatar6969** [azael1337/discord-nitro-sniper#4]
I tried to open it on termux, but when I choose option 1 it tells me this:
```
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Client.run.<locals>.runner() done, defined at /data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/client.py:577> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

**Comment by azael1337** [comment]
Bad token, are u putting a bot or user token?

**Comment by xAvatar6969** [comment]
> Bad token, are u putting a bot or user token?

where I need to put the token? I select the first option and it says that

**Comment by azael1337** [comment]
my bad for not writting that down:
where token goes: `self.token = ""` between the ""
line: `https://github.com/azael1337/discord-nitro-sniper/blob/master/main.py#L16`

must be a user token by the way
